---
title: "BASIC RASTER ANALYSIS WITH R"
author: "Anthony Kimpton"
date: "24/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(terra)

#https://geospatial-community.netlify.app/post/2022-02-23-raster-analysis/
```


```{r read}
x <- rast(nrows=108, ncols=108, xmin=0, xmax=10, ymin = 0, ymax = 10)
values(x) <- 1:ncell(x)

f <- system.file("ex/meuse.tif", package="terra") #example data within terra
r <- rast(f)
```

```{r plot}
plot(r)
```

```{r write}
x <- writeRaster(r, "output.tif", overwrite=TRUE)
```

```{r define_crs}
crs(x) <- "EPSG:27561" # this defines rather than changes
```

```{r layer_names}
s <- rast(system.file("ex/logo.tif", package="terra"))
names(s)

names(s) <- c("a", "b", "c")

names(s)
```

```{r subsetting_layers}
subset(s, 2:3) #will select band 2 and 3
#because we changed the names from red, green, blue to a, b c. 
s[[c("a", "b")]] #will also select band 2 and 3
s$a #will select the a (red) band
```

```{r raster_summary}
max_h <- global(r, "max", na.rm=TRUE) # The global() function can be used to extract values like the average, mean and max cell values.
max_h

hist(r)
```

```{r trim_ws}
trimmed <- trim(r)
plot(trimmed)
```

```{r aggregate}
agg <- aggregate(r, fact = 5, fun = 'mean')
plot(agg)
```

```{r resample}
origin(agg) <- c(10.5, 10.5)

rsm <- resample(r, agg, method= 'bilinear') #combining rasters from different sources and different origins and resolutions to match the resolution, the origin and the extent.
plot(rsm)
```

```{r overlay}
samp <- spatSample(r, 1, as.points=TRUE, na.rm=TRUE)

buf <- buffer(samp, width = 200)
plot(r)
plot(samp, add=TRUE)
plot(buf, add=TRUE)
```

```{r cropping}
cropped <- crop(r, buf) #crop is always a square whereas mask will do a true crop
plot(cropped)
```

```{r mask}
mask <- mask(r, buf)
mask <- trim(mask) #we can trim down all the NA values using the trim function
plot(mask)
```

```{r stretch}
str <- stretch(r) #normalises values to 0-255 (8bit)
global(str, "range", na.rm=TRUE)
```

```{r focal}
f <- focal(r, w=5, fun="mean") #cleans and smooths rasters
plot(f)
```

```{r raster_library}
library(raster)
stac <- stack(system.file("ex/logo.tif", package="terra")) #This is a raster stack
rst <- rast(stac) #now this is a SpatRaster

stac <- raster(rst) #now this is a RasterStack
```

# Realworld Example

```{r read2}
homefolder <- "C:/Users/uqakimpt/Downloads" #where did you download the files to?
chm_path <- paste0(homefolder, "/", "plot1_chm.tif") # canopy height
ortho_path <- paste0(homefolder, "/", "plot1_ortho_reduced.tif") # colour spectrum

#now read in the files using terra
chm <- rast(chm_path)
ortho <- rast(ortho_path)

#do the crs match?
crs(chm) == crs(ortho)
#do the origins match?
origin(chm) == origin(ortho)
#do the resolutions match?
res(chm) == res(ortho)
#do the extents match?
ext(chm) == ext(ortho)
```

```{r resample2}
chm_resampled <- resample(chm, ortho, method = "bilinear")
#now, geometry should match
res(chm_resampled) == res(ortho)
origin(chm_resampled) == origin(ortho)
ext(chm_resampled) == ext(ortho)
```

```{r}
plot(chm_resampled)
```

```{r}
plot(ortho)
```

```{r crop2}
chm_resampled <- trim(chm_resampled)
plot(chm_resampled)

ortho_cropped <- crop(ortho, chm_resampled)
```

```{r}
combined <- c(ortho_cropped, chm_resampled)
plot(combined)

names(combined) <- c('red', 'green', 'blue', 'chm')
```


```{r}
library(layer)
combined_lowres <- aggregate(combined, fact = 10) #10x less rows and columns

tilt_map_1 <- tilt_map(raster(combined_lowres$red))
tilt_map_2 <- tilt_map(raster(combined_lowres$green), x_shift = 0, y_shift = 50)
tilt_map_3 <- tilt_map(raster(combined_lowres$blue), x_shift = 0, y_shift = 100)
tilt_map_4 <- tilt_map(raster(combined_lowres$chm), x_shift = 0, y_shift = 150)

map_list <- list(tilt_map_1, tilt_map_2, tilt_map_3, tilt_map_4)

plot_tiltedmaps(map_list, 
                layer = c("value", "value", "value", "value"),
                palette = c("bilbao", "mako", "rocket", "turbo"),
                color = "grey40")

```

